### ISSUE TITLE
JAcK

### ISSUE THREAD

**Issue by Progamer1251718** [OMEGA6403/Osu-Maina#2]
wHy YoU coPy mE aHhhhhhHhhhHhhHHhhhhhHhHhhHHHHHHhhHhhhhhhHhHhHhhHhHHHhHhhHhHhHHhhhhhhhhHHHhhhhhHhh

**Comment by Progamer1251718** [comment]
wHy

**Comment by Progamer1251718** [comment]
JACK GUIVER ARNOLD HAH REAL NAME REAL

**Comment by Progamer1251718** [comment]
DELETE DIS

**Comment by OMEGA6403** [comment]
levon i forked this a year ago also yours is a copy of something different dumbass
